import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Legal Disclaimer',
  description: 'Legal disclaimer and terms of use for One Minute Event.',
}

export default function DisclaimerPage() {
  return (
    <div style={{ paddingTop: 'calc(var(--nav-height) + var(--space-16))', paddingBottom: 'var(--space-20)' }}>
      <div className="container" style={{ maxWidth: 760 }}>
        <div className="gold-line" style={{ marginBottom: 'var(--space-5)' }} />
        <h1 style={{ marginBottom: 'var(--space-8)' }}>Legal Disclaimer</h1>

        <section style={{ marginBottom: 'var(--space-8)' }}>
          <h2 style={{ fontSize: 'var(--text-2xl)', marginBottom: 'var(--space-4)' }}>Budget Estimates</h2>
          <p>
            All budget estimates generated by One Minute Event are indicative only and based on aggregated
            market data. Actual costs may vary based on specific supplier negotiations, seasonal pricing,
            and event requirements. One Minute Event accepts no liability for discrepancies between estimates
            and final contracted prices.
          </p>
        </section>

        <hr className="divider" />

        <section style={{ marginBottom: 'var(--space-8)' }}>
          <h2 style={{ fontSize: 'var(--text-2xl)', marginBottom: 'var(--space-4)' }}>Third-Party Suppliers</h2>
          <p>
            One Minute Event acts as a platform intermediary only. We do not endorse, warrant, or guarantee
            the services of any third-party supplier listed on the platform. All contractual obligations
            are between the couple and the individual supplier.
          </p>
        </section>

        <hr className="divider" />

        <section>
          <h2 style={{ fontSize: 'var(--text-2xl)', marginBottom: 'var(--space-4)' }}>Data &amp; Privacy</h2>
          <p>
            Personal data collected through this platform is processed in accordance with applicable data
            protection legislation. Your data is never sold to third parties. For full details, please
            refer to our Privacy Policy.
          </p>
        </section>
      </div>
    </div>
  )
}
